# Build Options
VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_SLEEP = yes
MIDI_ENABLE = no
COMBO_ENABLE = yes

# Reduce firmware size:
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no